### ISSUE TITLE
讲稿播放器里的图片加载优化

### ISSUE THREAD

**Issue by Martin91** [beansmile/jianggaowang#123]
![image](https://cloud.githubusercontent.com/assets/2900644/14983319/0dcfd3f0-116f-11e6-99a4-325babceb6e3.png)
现在的讲稿图片里面，尺寸太大导致加载太慢，有明显卡顿感。可以综合考虑以下优化方案：
1） 服务器端从 PDF 转图片的时候同时转换多尺寸，播放器里用小尺寸，全屏播放用大尺寸。或者像视频播放器一样，由用户自行选择分辨率；多尺寸也能方便手机端等小尺寸屏幕观看。
2） 服务器只负责 PDF -》 大尺寸图片的转换，然后图片上传到云存储，由云存储完成多尺寸图片处理，这样减轻服务器压力，本身也更灵活。用了云存储之后，再开个 CDN 就更好了。

**Comment by leondu** [comment]
cc @zhaqiang 

方案二应该很多云存储包括七牛都支持？

**Comment by zhaqiang** [comment]
@Martin91 @leondu 收到，优化图片加载这个会在基本功能都完成后跟进。

另方案二七牛是支持的。

**Comment by Martin288** [comment]
@leondu @zhaqiang 如果服务器是阿里云的，可以考虑用阿里云 OSS，一站式服务，同时可以利用内网优势确保上传速度以及稳定性。

**Comment by songjiayang** [comment]
需要尽早确定，现在下载速度比较慢

**Comment by Martin91** [comment]
@leondu @zhaqiang 这个问题是否已经有计划？没有的话我可以来提供PR，你们确认下是要七牛还是阿里云就行了。另外，我看现在网页上加载卡顿，可能是因为图片没有懒加载引起的，我觉得可以同时考虑懒加载的问题

**Comment by Martin91** [comment]
Solution:
1. 图片转换完成后自动上传到云存储；
2. 播放器图片懒加载；
3. 预览图片使用低尺寸照片。

**Comment by Martin91** [comment]
@leondu @zhaqiang PR 已经完成，完成了上面说的两个功能了。

**Comment by Martin288** [comment]
@zhaqiang 这个是否可以关闭了？
