### ISSUE TITLE
导航栏“标签”链接是空链接

### ISSUE THREAD

**Issue by Martin91** [beansmile/jianggaowang#125]
![image](https://cloud.githubusercontent.com/assets/2900644/14983451/1c976244-1170-11e6-95a0-4916ec21e7d8.png)

**Comment by zhaqiang** [comment]
@Martin91 这个 bug 已经写了 PR  [Slides tags index page](https://github.com/beansmile/jianggaowang/pull/118)，合并后就可以修复了。
