### ISSUE TITLE
有讲稿标题过长，讲稿块高度不一样，样式出现问题

### ISSUE THREAD

**Issue by hxx** [beansmile/jianggaowang#78]
http://jianggaowang.com/categories/hotest
有讲稿标题过长，讲稿块高度不一样，样式出现问题
13寸 rMBP Chrom Version 49.0.2623.110 (64-bit)
![image](https://cloud.githubusercontent.com/assets/4384971/14456994/7155f95e-00da-11e6-8cca-6f7a2f0440e9.png)

**Comment by Martin91** [comment]
可以指定标题行定高，超出高度就隐藏？

**Comment by chenbin92** [comment]
@Martin91 @hxx  正在开发新的版本，这个问题会处理掉了

**Comment by Martin91** [comment]
@chenbin92 Awesome，:D !
